/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

import com.google.common.math.BigIntegerMath;

import java.math.BigInteger;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }





    public static void main(String[] args) {
        Operation op = new Operation();
        Scanner scan = new Scanner(System.in);
        while (true) {
            Scanner scan2 = new Scanner(System.in);
            System.out.println("Input $ to exit.");
            System.out.println("What operation do you want to do ?");
            String operation = scan2.nextLine();
            if (operation.equalsIgnoreCase("$"))break;
            if (operation.equalsIgnoreCase("factorial")) {
                try {
                    System.out.println("\nInput the number:");
                    int number1 = scan.nextInt();
                    op.factorial(number1);
                }catch (Exception e){
                    System.out.println("Please enter a valid integer.");
                }

            } else {
                try {
                    System.out.println("\nInput the first number:");
                    int number1 = scan.nextInt();
                    System.out.println("\nInput the second number:");
                    int number2 = scan.nextInt();

                    switch (operation.toLowerCase()) {
                        case "addition", "+", "add" -> {

                            System.out.println(number1 + " + " + number2 + " = " + op.add(number1,number2));
                        }
                        case "subtract", "-", "minus" -> {
                            System.out.println(number1 + " - " + number2 + " = " + op.subtract(number1,number2));
                        }
                        case "multiply", "x", "*" -> {
                            System.out.println(number1 + " * " + number2 + " = " + op.multiply(number1,number2));
                        }
                        default -> System.out.println("please enter an actual operation.");
                    }
                }catch (Exception e)
                {
                    System.out.println("Please enter a valid integer.");
                }
            }
        }

    }
}
